name: Build

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-22.04, macos-12]
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build wheels
        working-directory: ./python
        run: |
          pip install wheel oldest-supported-numpy
          make wheel
        env:
          CC: gcc-12
          CXX: g++-12
          MACOSX_DEPLOYMENT_TARGET: 10.15

      - uses: actions/upload-artifact@v3
        with:
          path: ./python/dist/*.whl
